name: Go Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - internal/**
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Run Tests
        run: |
          go test -v -count 1 ./...