name: Terraform Apply
on:
  push:
    branches:
      - main
    paths:
      - infra/**
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: infra
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        id: init
        run: |
          terraform init
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve -no-color