name: Terraform Plan
on:
  pull_request:
    branches:
      - main
    paths:
      - infra/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: infra
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        id: init
        run: |
          terraform init
      - name: Terraform Format
        id: fmt
        run: |
          terraform fmt
      - name: Terraform Validate
        id: validate
        run: |
          terraform validate
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color
        continue-on-error: true